---
# tasks file for arista_eos
#
- name: set the role version
  set_fact:
    ansible_network_eos_version: "devel"

- name: display the role version to stdout
  debug:
    msg: "ansible_network.arista_eos version is {{ ansible_network_eos_version }}"

- name: validate ansible_network_os == 'eos'
  fail:
    msg: "this role only works with arista eos devices"
  when: ansible_network_os != 'eos'

- name: set role supported functions
  set_fact:
    eos_functions:
      - clear_sessions
      - load_config
      - get_facts
      - get_config
      - noop

- name: validate the requested function is supported
  fail:
    msg: "invalid function specified, expected one of {{ eos_functions }}, got {{ function }}"
  when: function | default('noop') not in eos_functions

- name: include function specific tasks and run
  include_tasks: "{{ function  | default('noop') }}.yaml"
