---
- name: initialize function
  include_tasks: includes/init.yaml

- name: validate required var is set
  fail:
    msg: "missing required argument: eos_config_includes"
  when: eos_config_includes is undefined

- name: create checkpoint file on remote device
  include_tasks: includes/checkpoint/create.yaml
  when: eos_rollback_enabled

- name: display message
  debug:
    msg: "eos configuration rollback is {{ eos_rollback_enabled | ternary('enabled', 'disabled') }}"

# check if the current target device supports the configure sessions feature.
# if config sessions is not suppported and config replace is enabled or
# required sessions is enabled, then fail the host
- name: check if device supports config sessions
  cli:
    command: "show configuration sessions"
  register: eos_supports_sessions
  ignore_errors: true

- name: fail host without config session support
  fail:
    msg: "configure sessions is not supported on this version of eos"
  when: eos_supports_sessions is failed

- name: edit the target device configuration
  block:
    - name: iterate over configuration tasks
      include_tasks: "{{ task }}"
      loop: "{{ eos_config_includes }}"
      loop_control:
        loop_var: task

  rescue:
    - name: restore checkpoint file
      include_tasks: includes/checkpoint/restore.yaml
      when: eos_rollback_enabled

    - name: fail host
      fail:
        msg: error loading configuration onto target host

- name: remove checkpoint file from remote device
  include_tasks: includes/checkpoint/remove.yaml
  when: eos_rollback_enabled
