---
- name: validate required argument
  fail:
    msg: "missing required argument: eos_config_text"
  when: eos_config_text is undefined or eos_config_text == ''

- name: display message
  debug:
    msg: "eos configuration rollback is {{ eos_rollback_enabled | ternary('enabled', 'disabled') }}"

# check if there is an old checkpoint file on the flash disk and remove it
# before continuing
- name: get current files on flash
  cli:
    command: dir
  register: eos_dir_listing

- name: delete old checkpoint file
  cli:
    command: "delete flash:{{ eos_config_checkpoint_filename }}"
  when: eos_config_checkpoint_filename in eos_dir_listing.stdout

# only create the checkpoint configuration file if rollback is currently
# enabled (default)
- name: checkpoint existing active configuration for rollback
  block:
    - name: create configuration checkpoint
      cli:
        command: "copy running-config flash:{{ eos_config_checkpoint_filename }}"
      register: eos_checkpoint_command

    - name: verify configuration checkpoint was successful
      fail:
        msg: "error attemping to create configuration checkpoint"
      when: eos_checkpoint_command.stdout != 'Copy completed successfully.'
  when: eos_rollback_enabled

# check if the current target device supports the configure sessions feature.
# if config sessions is not suppported and config replace is enabled or
# required sessions is enabled, then fail the host
- name: check if device supports config sessions
  cli:
    command: "show configuration sessions"
  register: eos_supports_sessions
  ignore_errors: true

- name: fail host without config session support
  fail:
    msg: "configure sessions is not supported on this version of eos"
  when: eos_supports_sessions is failed and (eos_config_replace or eos_config_require_session)

- name: configure target device
  block:
    - name: load configuration using configure session
      include_tasks: includes/configure_session.yaml
      when: eos_supports_sessions is success

    - name: load configuration using configure terminal
      include_tasks: includes/configure_terminal.yaml
      when: not ansible_check_mode and eos_supports_sessions is failed
  rescue:
    - name: display message
      debug:
        msg: "error configuration device, starting rollback"

    - name: configuration rollback pre hook
      include_tasks: "{{ eos_configuration_rollback_pre_hook }}"
      when: eos_configuration_rollback_pre_hook is defined and eos_rollback_enabled

    - name: rollback configuration
      cli:
        command: "configure replace flash:{{ eos_config_checkpoint_filename }}"
      when: eos_rollback_enabled

    - name: remove configuration checkpoint file
      cli:
        command: "delete flash:{{ eos_config_checkpoint_filename }}"
      when: eos_rollback_enabled

    - name: configuration rollback post hook
      include_tasks: "{{ eos_configuration_rollback_post_hook }}"
      when: eos_configuration_rollback_post_hook is defined and eos_rollback_enabled

    - name: display message
      debug:
        msg: "successfully completed configuration rollback"
      when: eos_rollback_enabled

    - name: fail host due to config load error
      fail:
        msg: "error loading configuration onto target device"

# clean up the temp files that are stored on the remote flash drive of the
# target host
- name: get current files on flash
  cli:
    command: dir
  register: eos_dir_listing

- name: delete old checkpoint file
  cli:
    command: "delete flash:{{ eos_config_checkpoint_filename }}"
  when: eos_config_checkpoint_filename in eos_dir_listing.stdout
